services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: novobanco-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-NovoBanco2026!}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD:-NovoBanco2026!}" -C -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD:-NovoBanco2026!}
    volumes:
      - ./database:/scripts
    command: bash /scripts/init.sh

  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: novobanco-api
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      DB_URL: jdbc:sqlserver://sqlserver:1433;databaseName=novobanco;trustServerCertificate=true
      DB_USERNAME: sa
      DB_PASSWORD: ${MSSQL_SA_PASSWORD:-NovoBanco2026!}
    ports:
      - "8080:8080"

volumes:
  sqlserver-data:
