# ===========================================
# Datasource Configuration
# ===========================================

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:1433;databaseName=novobanco;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:NovoBanco2026!}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===========================================
# JPA / Hibernate
# ===========================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===========================================
# Server
# ===========================================

server.port=8080
server.servlet.context-path=/api
