AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Secrets Manager for database credentials

Parameters:
  EnvironmentName:
    Type: String

  DBUsername:
    Type: String

Resources:
  DBSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub ${EnvironmentName}/db-credentials
      Description: RDS SQL Server credentials
      GenerateSecretString:
        SecretStringTemplate: !Sub '{"username": "${DBUsername}"}'
        GenerateStringKey: password
        PasswordLength: 20
        ExcludeCharacters: '"@/\'

Outputs:
  DBSecretArn:
    Value: !Ref DBSecret
